stages:
  - publish

publish:
  stage: publish
  image: ortussolutions/commandbox
  only:
    - tags
  script:
    - box forgebox login ${FORGE_USER} ${FORGE_PASS}
    - box bump version=${CI_COMMIT_TAG} tagVersion=false
    - box publish

