stages:
  - build
  - publish

set_version:
  stage: build
  only:
    - tags
  script:
    - sed -ri "s|0.0.1|${CI_COMMIT_TAG}|" box.json

publish:
  stage: publish
  image: ortussolutions/commandbox
  only:
    - tags
  script:
    - box forgebox login ${FORGE_USER} ${FORGE_PASS}
    - box publish

